version: '3'

services:
  workstation:
    build: .
    image: haxagon/workstation-sysbox
    hostname: haxagon
    runtime: sysbox-runc
    tty: true
    environment:
      - USERNAME=student
      - PASSWORD=password
      - SUDO=true
      - WEB_SHELL_PORT=8080
#      - READY=false
    ports:
      - "22:22"
      - "8080:8080"
