version: '3'

services:
  workstation:
    build: .
    image: haxagon/workstation-sysbox
    runtime: sysbox-runc
    tty: true
    environment:
      - AMDIN_PASSWORD=mypassword
    ports:
      - "22:22"
      - "7681:7681"
