version: '3'

services:
  workstation:
    build: .
    image: haxagon/workstation-sysbox:edge
    hostname: haxagon
    runtime: sysbox-runc
    tty: true
    environment:
      - USERNAME=student
      - PASSWORD=password
      - SUDO=true
#      - READY=false
    ports:
      - "22:22"
      - "7681:7681"
